services:
  - type: web
    name: tc-fulfilment-assessment
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:application
    healthCheckPath: /health
